version: '3.8'  # Version of Docker Compose specification used.

services:
  ansible-container:  # Name of the service.
    build: 
      context: .  # Path to the directory containing the Dockerfile and source code.
      dockerfile: Dockerfile  # Name of the Dockerfile.
    image: ${DOCKERHUB_USERNAME}/repository:latest  # Name of the Docker image. Replace 'repository' with the desired name for your DockerHub repository.
    volumes:
      - ./ansible:/ansible  # Bind the local "ansible" directory to the "/ansible" directory in the container.
      - ~/.ssh/ansible:/home/ansible/.ssh  # Bind local SSH keys to the container.
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False  # To prevent Ansible from asking to confirm connection with an unknown host.
    command: ["ansible", "--version"]  # Default command to execute when the container starts.

# Here you can add networks, volumes, and other top-level configurations if needed.
