name: Docker CI/CD

on:
  push:
    paths-ignore:
      - '**.md'
      - './docs/**'
      - './img/**'
      - './Makefile'
    branches:
      - main
      - develop
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'release/**'
    tags:
      - 'v*.*.*'

  pull_request:
    paths-ignore:
      - '**.md'
      - './docs/**'
      - './img/**'
      - './Makefile'
    branches:
      - main
      - develop
      - 'release/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract Repo Name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | sed -e 's#.*/docker-##')" >> $GITHUB_ENV

      - name: Set APP_VERSION
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "APP_VERSION=$(echo ${{ github.ref }} | sed -e 's#refs/tags/##')" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/heads/main ]]; then
            if [[ "${{ github.event.pull_request.head.ref }}" == release/v* ]]; then
              echo "APP_VERSION=$(echo ${{ github.event.pull_request.head.ref }} | sed -e 's#release/v##')-beta" >> $GITHUB_ENV
            else
              echo "APP_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))-alpha" >> $GITHUB_ENV
            fi
          elif [[ "${{ github.ref }}" == refs/heads/develop ]]; then
            echo "APP_VERSION=develop" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/heads/feature/* ]]; then
            echo "APP_VERSION=feature-$(echo ${{ github.ref }} | sed -e 's#refs/heads/feature/##')" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/heads/bugfix/* ]]; then
            echo "APP_VERSION=bugfix-$(echo ${{ github.ref }} | sed -e 's#refs/heads/bugfix/##')" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/heads/hotfix/* ]]; then
            echo "APP_VERSION=hotfix-$(echo ${{ github.ref }} | sed -e 's#refs/heads/hotfix/##')" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
            echo "APP_VERSION=$(echo ${{ github.ref }} | sed -e 's#refs/heads/release/##')-beta" >> $GITHUB_ENV
          fi

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ env.APP_VERSION }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
