name: Docker CI/CD

on:
  push:
    paths-ignore:
      - '**.md'
      - './docs/**'
      - './img/**'
      - './Makefile'
    branches:
      - main
      - develop
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'
    tags:
      - 'v*.*.*'

  pull_request:
    paths-ignore:
      - '**.md'
      - './docs/**'
      - './img/**'
      - './Makefile'
    branches:
      - main
      - develop

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

name: Docker CI/CD

on:
  push:
    paths-ignore:
      - '**.md'
      - './docs/**'
      - './img/**'
      - './Makefile'
    branches:
      - main
      - develop
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'
    tags:
      - 'v*.*.*'

  pull_request:
    paths-ignore:
      - '**.md'
      - './docs/**'
      - './img/**'
      - './Makefile'
    branches:
      - main
      - develop

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate Hotfix Version
        run: |
          if [[ "${{ github.ref }}" == refs/heads/hotfix/* ]]; then
            # Extract the proposed version from the branch name
            PROPOSED_VERSION=$(echo ${{ github.ref }} | sed -e 's#refs/heads/hotfix/v##')
            
            # Get the latest tag
            LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
            
            # Extract the minor version from the latest tag
            LATEST_MINOR_VERSION=$(echo $LATEST_TAG | awk -F. '{print $2}')
            
            # Extract the minor version from the proposed version
            PROPOSED_MINOR_VERSION=$(echo $PROPOSED_VERSION | awk -F. '{print $2}')
            
            # Validate the minor version
            if ((PROPOSED_MINOR_VERSION != LATEST_MINOR_VERSION + 1)); then
              echo "Error: Invalid hotfix version. Minor version should be incremented by 1."
              exit 1
            fi
          fi

      - name: Extract Repo Name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | sed -e 's#.*/docker-##')" >> $GITHUB_ENV

      - name: Set APP_VERSION
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            ORIGINAL_BRANCH=${{ github.event.pull_request.head.ref }}
            case "$ORIGINAL_BRANCH" in
              release/v*)
                echo "APP_VERSION=$(echo $ORIGINAL_BRANCH | sed -e 's#release/v##')-beta" >> $GITHUB_ENV
                ;;
              hotfix/v*)
                echo "APP_VERSION=$(echo $ORIGINAL_BRANCH | sed -e 's#hotfix/v##')-beta" >> $GITHUB_ENV
                ;;
              *)
                echo "APP_VERSION=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
                ;;
            esac
          else  # For push events
            case "${{ github.ref }}" in
              refs/tags/*)
                echo "APP_VERSION=$(echo ${{ github.ref }} | sed -e 's#refs/tags/##')" >> $GITHUB_ENV
                ;;
              refs/heads/main)
                echo "APP_VERSION=latest-alpha" >> $GITHUB_ENV
                ;;
              refs/heads/develop)
                echo "APP_VERSION=develop" >> $GITHUB_ENV
                ;;
              refs/heads/feature/*)
                echo "APP_VERSION=feature-$(echo ${{ github.ref }} | sed -e 's#refs/heads/feature/##')" >> $GITHUB_ENV
                ;;
              refs/heads/hotfix/*)
                echo "APP_VERSION=hotfix-$(echo ${{ github.ref }} | sed -e 's#refs/heads/hotfix/##')" >> $GITHUB_ENV
                ;;
              refs/heads/release/*)
                echo "APP_VERSION=$(echo ${{ github.ref }} | sed -e 's#refs/heads/release/##')-beta" >> $GITHUB_ENV
                ;;
              *)
                echo "APP_VERSION=unknown" >> $GITHUB_ENV
                ;;
            esac
          fi

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ env.APP_VERSION }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
        
      - name: Extract Repo Name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | sed -e 's#.*/docker-##')" >> $GITHUB_ENV

      - name: Set APP_VERSION
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            ORIGINAL_BRANCH=${{ github.event.pull_request.head.ref }}
            case "$ORIGINAL_BRANCH" in
              release/v*)
                echo "APP_VERSION=$(echo $ORIGINAL_BRANCH | sed -e 's#release/v##')-beta" >> $GITHUB_ENV
                ;;
              hotfix/v*)
                echo "APP_VERSION=$(echo $ORIGINAL_BRANCH | sed -e 's#hotfix/v##')-beta" >> $GITHUB_ENV
                ;;
              *)
                echo "APP_VERSION=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
                ;;
            esac
          else  # For push events
            case "${{ github.ref }}" in
              refs/tags/*)
                echo "APP_VERSION=$(echo ${{ github.ref }} | sed -e 's#refs/tags/##')" >> $GITHUB_ENV
                ;;
              refs/heads/main)
                echo "APP_VERSION=latest-alpha" >> $GITHUB_ENV
                ;;
              refs/heads/develop)
                echo "APP_VERSION=develop" >> $GITHUB_ENV
                ;;
              refs/heads/feature/*)
                echo "APP_VERSION=feature-$(echo ${{ github.ref }} | sed -e 's#refs/heads/feature/##')" >> $GITHUB_ENV
                ;;
              refs/heads/hotfix/*)
                echo "APP_VERSION=hotfix-$(echo ${{ github.ref }} | sed -e 's#refs/heads/hotfix/##')" >> $GITHUB_ENV
                ;;
              refs/heads/release/*)
                echo "APP_VERSION=$(echo ${{ github.ref }} | sed -e 's#refs/heads/release/##')-beta" >> $GITHUB_ENV
                ;;
              *)
                echo "APP_VERSION=unknown" >> $GITHUB_ENV
                ;;
            esac
          fi

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ env.APP_VERSION }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
