name: Docker CI/CD

on:
  push:
    paths-ignore:
      - '**.md'
      - './docs/**'
      - './img/**'
      - './Makefile'
    branches:
      - main
      - develop
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'release/**'
    tags:
      - 'v*.*.*'

  pull_request:
    paths-ignore:
      - '**.md'
      - './docs/**'
      - './img/**'
      - './Makefile'
    branches:
      - main
      - develop
      - 'release/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract Repo Name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | sed -e 's#.*/docker-##')" >> $GITHUB_ENV

      - name: Set APP_VERSION
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "APP_VERSION=$(echo ${{ github.ref }} | sed -e 's#refs/tags/##')" >> $GITHUB_ENV
          else
            echo "APP_VERSION=sha-${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}
          tags: |
            type=semver,pattern={{version}},value=latest
            type=semver,pattern={{version}}
            type=ref,event=branch,value=latest
            type=sha,format=short

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.REPO_NAME }}:${{ env.APP_VERSION }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
