name: Create Pull Request

on:
  push:
    branches:
      - feature/**
      - bugfix/**
      - hotfix/**
      - release/**

jobs:
  createPR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Pull Request
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          gh auth login --with-token $MY_GITHUB_TOKEN
          case "${{ github.ref }}" in
            refs/heads/feature/*|refs/heads/bugfix/*)
              gh pr create --base develop --head ${{ github.ref }} --title "Automated PR from ${{ github.ref }}" --body "This is an automated pull request."
              ;;
            refs/heads/hotfix/*|refs/heads/release/*)
              gh pr create --base main --head ${{ github.ref }} --title "Automated PR from ${{ github.ref }}" --body "This is an automated pull request."
              ;;
          esac
