# Docker CI/CD for Develop Branch
name: Develop Docker Build and Push

# Trigger this workflow only for pushes to the develop branch
on:
  push:
    branches:
      - develop

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Extract the repository name and set it as an environment variable
      - name: Extract Repo Name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | sed -e 's#.*/docker-##')" >> $GITHUB_ENV

      # Set APP_VERSION
      - name: Set APP_VERSION
        run: echo "APP_VERSION=develop" >> $GITHUB_ENV

      # Setup Docker with Buildx (for multi-platform builds)
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      # Log in to DockerHub
      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ env.APP_VERSION }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
