# Docker CI/CD for Main Branch
name: Main Docker Build and Push

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  docker:
    if: github.event.pull_request.merged == true && ( startsWith(github.event.pull_request.head.ref, 'hotfix/') || startsWith(github.event.pull_request.head.ref, 'release/') )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate Version Update
        run: |
          NEW_VERSION=$(echo ${{ github.event.pull_request.head.ref }} | sed -e 's#hotfix/##' -e 's#release/##')
          OLD_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          IFS='.' read -ra NEW_VER_PARTS <<< "$NEW_VERSION"
          IFS='.' read -ra OLD_VER_PARTS <<< "$OLD_VERSION"

          if [[ "${{ github.event.pull_request.head.ref }}" == hotfix/* ]]; then
            # Only minor version update is allowed for hotfix
            if [[ "${NEW_VER_PARTS[2]}" -ne $((${OLD_VER_PARTS[2]} + 1)) ]]; then
              echo "Invalid hotfix version. Only minor update allowed."
              exit 1
            fi
          elif [[ "${{ github.event.pull_request.head.ref }}" == release/* ]]; then
            # Major and minor version update are allowed for release
            if [[ "${NEW_VER_PARTS[0]}" -lt "${OLD_VER_PARTS[0]}" || "${NEW_VER_PARTS[1]}" -lt "${OLD_VER_PARTS[1]}" ]]; then
              echo "Invalid release version. Only major and minor updates allowed."
              exit 1
            fi
          fi

      - name: Set APP_VERSION
        run: echo "APP_VERSION=$(echo ${{ github.event.pull_request.head.ref }} | sed -e 's#hotfix/##' -e 's#release/##')" >> $GITHUB_ENV

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ env.APP_VERSION }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
